### ISSUE TITLE
activating deepjetpkg by sourcing lxplus_env.sh / gpu_env.sh

### ISSUE THREAD

**Issue by rishabhCMS** [DL4Jets/DeepJet#7]
https://github.com/SwapneelM/DeepJet
while trying to follow the instructions for activating the environment using

`source lxplus_env.sh / gpu_env.sh `

> export PATH=$DEEPJETCORE/bin:$PATH
> : No such file or directory

but if I try to activate to activate using 
`source pypkg_env.sh`
the deepjetpkg activates with no issue

**Is this something which can be an issue while training?**

**Comment by SwapneelM** [comment]
Should not be an issue since this error is due to a poorly maintained script across branches and versions.
